name: mega_cli
description: A new Flutter project.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  cli_dialog: ^0.5.0
  cli_menu: ^0.2.3
  dart_style: 
  http: ^0.13.3
  process_run: ^0.12.1+1
  pubspec: ^2.0.1
  recase: ^4.0.0
  version: ^2.0.0
  

executables:
  mega: mega
  megas: mega
