name: mega_cli
description: A new Flutter project.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  cli_dialog: ^0.5.0
  cli_menu: ^0.3.0-nullsafety.0 
  dart_style: null
  http: ^0.13.3
  intl: ^0.17.0
  process_run: ^0.12.1+1
  pubspec: ^2.0.1
  recase: ^4.0.0
  version: ^2.0.0

dev_dependencies:
  analyzer: ^2.0.0

executables:
  mega: mega
  megas: mega
